exports.sanduiches = [
    { id: 100, title: 'NOME_SANDUICHE A', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 101, title: 'NOME_SANDUICHE B', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 102, title: 'NOME_SANDUICHE C', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 103, title: 'NOME_SANDUICHE D', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 104, title: 'NOME_SANDUICHE E', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 105, title: 'NOME_SANDUICHE F', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 106, title: 'NOME_SANDUICHE G', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 107, title: 'NOME_SANDUICHE H', price: `R$ ${10.50}`, text_description: 'Descrição completa sobre o sancuíche', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/sanduiche.png', item1: 'Item 1', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
]

exports.bebidas = [
    { id: 200, title: 'Bebida A', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 201, title: 'Bebida B', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 202, title: 'Bebida C', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 203, title: 'Bebida D', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 204, title: 'Bebida E', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 205, title: 'Bebida F', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
    { id: 206, title: 'Bebida G', price: `R$${0.50}`, text_description: 'Descrição bebida', image: 'https://raw.githubusercontent.com/httpsdfaa/hamburgueria-site/main/assets/coca-cola.jpg', item1: '600 ml', item2: 'item 2', item3: 'Item N', item4: '', item5: '', item6: '', item7: '' },
]